blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/ZnmFrPvXym
    about: Ask questions and chat with the community
  - name: Documentation
    url: https://wangjiake.github.io/riverse-docs/
    about: Read the full documentation
